#!/usr/bin/env bash

aplay () {
  sudo ansible-playbook -i inventory.yaml --vault-password-file=~/.ansible/ansible_vault_password "${@}"
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || aplay "$@"
