#!/usr/bin/env bash

arun () {
  cd ~/ansible/ || return
  sudo ansible -i inventory.yaml "${@}"
  cd - >/dev/null
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || arun "$@"
