#!/usr/bin/env bash

arun () {
  cd ~/sovrn-repos/edi/ || return
  sudo ansible -i edi.py "${@}"
  cd - >/dev/null
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || arun "$@"
