#!/usr/bin/env bash

flogs () { # find logs and print
  find -L "$1" -maxdepth 1 -type f -iname "*.log" | \
    while read -r l ; do
      echo -e "\n$l\n"
      tail -n 200 "$l" | LC_ALL=C grep -iPC2 'err|fatal|except|fail|caused by|\tat\s'
    done \
  |& less -SIr
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || flogs "$@"
