#!/usr/bin/env bash

gpull () {
  local branch="$(git branch | awk '/*/{print $2}')"
  if [ "${branch}" = "master" ]; then
    git pull origin "${branch}"
    git fetch --prune
  else
    git pull origin "${branch}"
    git pull origin master
  fi
}

# This allows the function to be run as a script if this file is executed directly
[[ $- == *i* ]] || gpull "$@"
