#!/usr/bin/env bash

gpull () {
  local branch="$(git branch | awk '/*/{print $2}')"
  git pull origin "${branch}" || return $?
  [ "${branch}" = "master" ] || git pull origin master || return $?
  git fetch --prune
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || gpull "$@"
