#!/usr/bin/env bash

gpush () {
  local branch="$(git branch | awk '/*/{print $2}')"
  local message="${*}"
  if [ -z "${message}" ]; then
    echo "ERROR: Commit message empty."
    return 1
  fi
  gpull
  git commit -am "${message}" || return 1
  git push origin "${branch}"
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || gpush "$@"
