#!/usr/bin/env bash

gpush () {
  local branch="$(git branch | awk '/*/{print $2}')"
  gpull || return $?
  git commit -a || return $?
  git push origin "${branch}"
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || gpush "$@"
