#!/usr/bin/env bash

kreset () {
  # restart kde plasma
  kquitapp5 plasmashell &>/dev/null
  kstart5 plasmashell &>/dev/null
}

# This allows the function to be run as a script if this file is executed directly
[[ $- == *i* ]] || kreset "$@"
