#!/usr/bin/env bash

kreset () {
  # restart kde plasma
  kquitapp6 plasmashell &>/dev/null
  kstart plasmashell &>/dev/null
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || kreset "$@"
