#!/usr/bin/env bash

nooom () {
  launch_opts=(
      systemd-run
      --user
      --service-type=exec
      --same-dir
      --pty
      --pipe
      -p OOMScoreAdjust=1000
      -p OOMPolicy=kill
      -p MemoryLow=10%
      -p MemoryHigh=50%
      -p MemoryMax=75%
      "${@}"
  )
 "${launch_opts[@]}"
}

# This allows the function to be run as a script if this file is executed directly
[[ $- == *i* ]] || nooom "$@"
