#!/usr/bin/env bash

requireuser () {
  # Checks to see if current user matches $REQUIREUSER and exits if not.
  # REQUIREUSER can be set as a variable or passed in as an argument.
  # Usage: requireuser [user]
  local REQUIREUSER="${1:-${REQUIREUSER:-}}"
  if [ -z "${REQUIREUSER:-}" ] ; then
    quit "ERROR" "requireuser was called, but \$REQUIREUSER is not set"
  elif [ "$REQUIREUSER" != "$USER" ] ; then
    quit "ERROR" "Only $REQUIREUSER is allowed to run this script"
  else
    log "DEBUG" "User '$USER' matches '$REQUIREUSER' and is allowed to run this script"
  fi
}

# This allows the function to be run as a script if this file is executed directly
[[ $- == *i* ]] || requireuser "$@"
