#!/usr/bin/env bash

reset () {
  for m in u b ; do
    sudo sync
    sudo tee /proc/sysrq-trigger <<< $m
  done
}

# This allows the function to be run as a script if this file is executed directly
[[ $- == *i* ]] || reset "$@"
