#!/usr/bin/env bash

rssh () {
  until ssh "${@}" exit ; do true ; done ; ssh "${@}"
}

# This allows the function to be run as a script if this file is executed directly
[[ $- == *i* ]] || rssh "$@"
