#!/usr/bin/env bash

rssh () {
  # Retries ssh connections until ssh exits cleanly
  local host=""
  local sargs=()
  while ((${#})) ; do
    case "${1}" in
      (-*) sargs+=("${1}") ; shift ;;
      (*) host="${1}" ; shift ; break ;;
    esac
  done
  local args=("${@}")
  until ssh -o ConnectTimeout=5 "${sargs[@]}" "${host}" exit ; do true ; done
  ssh "${sargs[@]}" "${host}" "${args[@]}"
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || rssh "$@"
