#!/usr/bin/env bash

function set_var() {
  # call option with parameters: $1=name $2=value $3=file
  name="${1//\//\\/}"
  value="${2//\//\\/}"
  sed -i \
      -e '/^#\?\(\s*'"${name}"'\s*=\s*\).*/{s//\1'"${value}"'/;:a;n;ba;q}' \
      -e '$a'"${name}"'='"${value}" $3
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || aplay "$@"
