#!/usr/bin/env bash

function set_var() {
  # call option with parameters: $1=key $2=value $3=file
  key="${1//\//\\/}"
  value="${2//\//\\/}"
  file="${3}"
  grep -q "${key}" "${file}" || tee -a "${file}" <<< "${key}=${value}" > /dev/null
  sudo sed -i \
      -e '/^#\?\(\s*'"${key}"'\s*=\s*\).*/{s//\1'"${value}"'/;:a;n;ba;q}' \
      -e '$a'"${key}"'='"${value}" "${file}"
}

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || aplay "$@"
