#!/usr/bin/env bash

start-agent () {
  pgrep -q ssh-agent || ssh-agent -sa "$HOME/.ssh/agent.sock" > /dev/null
  export SSH_AUTH_SOCK="$HOME/.ssh/agent.sock"
  export SSH_AGENT_PID="$(pgrep -afo ssh-agent)"
}

start-agent
