#!/usr/bin/env bash

start-agent () {
  export SSH_AUTH_SOCK="${HOME}/.ssh/agent.sock"
  ps aux | grep -q ssh-agent || {
    rm "${SSH_AUTH_SOCK}"
    ssh-agent -sa "${SSH_AUTH_SOCK}" > /dev/null
    export SSH_AGENT_PID="$(ps aux | awk '/ssh-agent/{print $1;exit}')"
  }
}

start-agent
