#!/usr/bin/env bash

get__bar () {
  curl -SL# http://www.theiling.de/downloads/bar-1.4-src.tar.bz2 \
    | tar --no-same-owner --strip-components=1 -xvjC "$HOME/bin" bar-1.4/bar
}

get__catimg () {
  local url="$(
    curl -sSL https://api.github.com/repos/posva/catimg/releases \
      | awk -F \" "/zipball_url/{ print \$4 ; exit }"
    )"
  curl -SL# "$url" > /tmp/catimg.zip || return
  unzip -oj \
    /tmp/catimg.zip \
    *catimg \
    -d "$HOME/bin"
  rm -v /tmp/catimg.zip
}

get__conspy () {
  local build_dir="/tmp/conspy"
  mkdir -vp "$build_dir"
  curl -SL# https://cfhcable.dl.sourceforge.net/project/conspy/conspy-1.14-1/conspy-1.14.tar.gz \
    | tar --no-same-owner --strip-components=1 -xzvC "$build_dir"
  cd "$build_dir"
  make || return
  sudo make install
  cd -
  rm -rf "$build_dir"
}

get__dategrep () {
  cpan App::dategrep
}

get__distribution () {
  curl -SL# -o "$HOME/bin/distribution" https://raw.githubusercontent.com/philovivero/distribution/master/distribution.py
  chmod a+x "$HOME/bin/distribution"
}

get__gosu () {
  case "$(uname -sm)" in
    "Linux x86_64")
      local url="$(
        curl -sSL https://api.github.com/repos/tianon/gosu/releases \
          | awk -F \" "/browser_download_url.*amd64/{ print \$4 ; exit }"
        )"
      curl -SL# "$url" > "$HOME/bin/hub"
    ;;
    *) echo "Unknown platform: $(uname -sm)" ; return ;;
  esac
}

get__hub () {
  case $(uname) in
    *inux) local arch=linux-amd64 ;;
    *arwin) local arch=darwin-amd64 ;;
    *) echo "Unknown platform: $(uname)" ; return ;;
  esac
  local url="$(
    curl -sSL https://api.github.com/repos/github/hub/releases \
      | awk -F \" "/browser_download_url.*${arch}/{ print \$4 ; exit }"
    )"
  local version="$(awk -F / '{print $8}' <<< "$url" | grep -o '[0-9\.]+')"
  curl -SL# "$url" \
    | tar --no-same-owner --strip-components=2 -xzvC "$HOME/bin" \
        "hub-${arch}-${version}/bin/hub"
}

get__jq () {
  case $(uname) in
    *inux) local arch=linux64 ;;
    *arwin) local arch=osx-amd64 ;;
    *) echo "Unknown platform: $(uname)" ; return ;;
  esac
  local url="$(
    curl -sSL https://api.github.com/repos/stedolan/jq/releases \
      | awk -F \" "/browser_download_url.*${arch}/{ print \$4 ; exit }"
    )"
  curl -SL# -o "$HOME/bin/jq" "$url"
  chmod a+x "$HOME/bin/jq"
}

get__lnav () {
  case $(uname) in
    *inux) local arch=linux-64bit ;;
    *arwin) local arch=os-x ;;
    *) echo "Unknown platform: $(uname)" ; return ;;
  esac
  local url="$(
    curl -sSL https://api.github.com/repos/tstack/lnav/releases \
      | awk -F \" "/browser_download_url.*${arch}.zip/{ print \$4 ; exit }"
    )"
  curl -SL# -o /tmp/lnav.zip "$url" || return
  unzip -oj \
    /tmp/lnav.zip \
    *lnav \
    -d "$HOME/bin"
  rm -v /tmp/lnav.zip
}

get__massren () {
  local GOPATH="$HOME"
  go get -u github.com/laurent22/massren
  go install github.com/laurent22/massren
}

get__ni () {
  curl -SL# https://github.com/spencertipping/ni/archive/develop.tar.gz \
    | tar --no-same-owner -xzvC "$HOME/bin/"
  ln -sv "$HOME/bin/ni-develop/ni" "$HOME/bin/ni"
}

get__nms () {
  local build_dir="/tmp/nms"
  mkdir -vp "$build_dir"
  curl -SL# https://github.com/bartobri/no-more-secrets/archive/master.tar.gz \
    | tar --no-same-owner --strip-components=1 -xzvC "$build_dir"
  cd "$build_dir"
  make
  cp bin/nms "$HOME/bin/nms"
  cd -
  rm -fr "$build_dir"
}

get__parallel () {
  local url="https://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2"
  local base="$(curl -sSL $url | tar -tj | head -n1)"
  curl -SL# "$url" \
    | tar --no-same-owner --strip-components=2 -xvjC "$HOME/bin" \
        "${base}src/env_parallel" \
        "${base}src/env_parallel.bash" \
        "${base}src/niceload" \
        "${base}src/parallel" \
        "${base}src/parcat" \
        "${base}src/parset" \
        "${base}src/sem" \
        "${base}src/sql" 
}

get__progress () {
  local build_dir="/tmp/progress"
  mkdir -vp "$build_dir"
  curl -SL# https://github.com/Xfennec/progress/archive/master.tar.gz \
    | tar --no-same-owner --strip-components=1 -xzvC "$build_dir"
  cd "$build_dir"
  make
  cp -v progress $HOME/bin/progress
  cd -
  rm -fr "$build_dir"
}

get__pup () {
  local GOPATH="$HOME"
  go get github.com/ericchiang/pup
  go install github.com/ericchiang/pup
}

get__pyenv () {
  mkdir -vp "$HOME/.pyenv"
  curl -SL# https://github.com/pyenv/pyenv/archive/master.tar.gz \
    | tar --no-same-owner --strip-components=1 -xzvC "$HOME/.pyenv"
  ln -sv "$HOME/.pyenv/bin/pyenv" "$HOME/bin/pyenv"
}

get__q () {
  curl -SL# -o "$HOME/bin/q" https://raw.githubusercontent.com/harelba/q/master/bin/q
  chmod a+x "$HOME/bin/q"
}

get__spark () {
  curl -SL# -o "$HOME/bin/spark" https://raw.githubusercontent.com/holman/spark/master/spark
  chmod a+x "$HOME/bin/spark"
}

get__speedtest () {
  curl -SL# -o "$HOME/bin/speedtest" https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
  chmod a+x "$HOME/bin/speedtest"
}

get__suplemon () {
  sudo pip3 install --upgrade suplemon
}

get__tldr () {
  curl -SL# -o "$HOME/bin/tldr" https://4e4.win/tldr
  chmod a+x "$HOME/bin/tldr"
  tldr -u
}

get_binaries () {
  mkdir -vp "$HOME/bin"
  declare -F | grep -o '(?<=\s)get__\S+' \
    | while read -r func ; do
        hr
        echo "Running $func"
        eval $func
      done
}
