#!/usr/bin/env bash
# set -x

for r in aliases/* functions/* options vars/* ; do
  source ${r}
done

[ -d "${HOME}/.bash_completion.d" ] &&
for c in "${HOME}/.bash_completion.d"/*; do
  source "${c}"
done || true

# load vault
[ -f ~/.vaultrc ] && source ~/.vaultrc |& logger -t vaultrc || true

# Source extra Mac stuff if on a Mac
[[ "$(uname)" == 'Darwin' ]] && source "$PWD/osx" || true

[ -f "/usr/share/nvm/init-nvm.sh" ] && source /usr/share/nvm/init-nvm.sh || true

set +x
