#!/usr/bin/env bash

for r in aliases/* functions/* get_binaries options vars/* liquidpromptrc liquidprompt ;do
# for r in aliases/* functions/* get_binaries options vars/* ; do
  source ${r}
done

# load vault
[ -f ~/.vaultrc ] && source ~/.vaultrc |& logger -t vaultrc

# Source extra Mac stuff if on a Mac
[[ "$(uname)" == 'Darwin' ]] && source "$PWD/osx"

# # Enable Bash completion
# source "bash-completion/bash_completion"

# PROMPT_COMMAND=promptline
