#!/usr/bin/env bash

# Replace PATH
export PATH="$(
tr '\n' ':' << EOF
$HOME/bin
$HOME/go/bin
$HOME/.cargo/bin
$HOME/.local/bin
/usr/local/opt/coreutils/libexec/gnubin
/usr/local/opt/grep/libexec/gnubin
/usr/local/opt/gnu-tar/libexec/gnubin
/usr/local/opt/gnu-sed/libexec/gnubin
/Users/jmccoy/Library/Python/3.7/bin
/opt/X11/bin
/opt/local/bin
/opt/local/sbin
/opt/bin
/opt/sbin
/usr/lib/mit/bin
/usr/lib/mit/sbin
/usr/local/Cellar
/usr/local/bin
/usr/local/sbin
/usr/bin
/usr/sbin
/bin
/sbin
$HOME/bin/morpheus
EOF
)"

# History settings
export HISTCONTROL=ignoredups:ignorespace
export HISTSIZE=4000
export HISTFILESIZE=8000
export HISTTIMEFORMAT="%d/%m/%y %T "

# Start SSH agent
export SSH_ENV="$HOME/.ssh/environment"
start_agent () {
  echo "Initialising new SSH agent..."
  ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
  echo succeeded
  chmod 600 "${SSH_ENV}"
  source "${SSH_ENV}" > /dev/null
  ssh-add
}
if [ -f "${SSH_ENV}" ]; then
  source "${SSH_ENV}" > /dev/null
  ps -ef | grep ${SSH_AGENT_PID} | grep 'ssh-agent$' > /dev/null || { start_agent; }
elif [[ $- == *i* ]] ; then
  start_agent;
fi

# Enable Bash completion
source "bash-completion/bash_completion"

# Set a cooler prompt for git and stuff
source "bash-git-prompt/gitprompt.sh"
export GIT_PROMPT_ONLY_IN_REPO=0
export GIT_PROMPT_THEME="Single_line_Minimalist"

# Source bblib and remove unwanted traps
source "bblib/bblib.bash"
trap - INT TERM QUIT HUP EXIT ERR

# Source my settings
source aliases
source colors
source functions
source options
source get_binaries
[ -f ~/.vaultrc ] && source ~/.vaultrc |& logger -t vaultrc

# Source extra Mac stuff if on a Mac
[[ "$(uname)" == 'Darwin' ]] && source "$PWD/osx"

export GOPATH=$HOME/go

# Load pyenv
# if [ -d "$HOME/.pyenv" ] && which pyenv 2>&1 > /dev/null ; then
#   export PATH="$HOME/.pyenv/bin:$HOME/.pyenv/shims:$PATH"
#   eval "$(pyenv init -)"
#   eval "$(pyenv virtualenv-init -)"
# # else
# #   logger -st bash_env:osx "ERROR: pyenv is not installed."
# fi

# git pull 2>&1 >/dev/null & disown
# git submodule update --recursive --remote  2>&1 >/dev/null & disown
