#!/usr/bin/env bash

# Exports for Homebrew
export PATH="/usr/local/Cellar:/opt/local/bin:/opt/local/sbin:$PATH"

# Prepend stuff to PATH
export PATH="$(
tr '\n' ':' << EOF
$(tr ':' '\n' <<< "$PATH")
/opt/X11/bin
/opt/local/bin
/opt/local/sbin
/usr/lib/mit/sbin
/usr/local/Cellar
EOF
)"

export MANPATH=/opt/local/share/man:$MANPATH
export DISPLAY=:0.0
