#!/usr/bin/env bash

# Exports for Homebrew
export PATH="/usr/local/Cellar:/opt/local/bin:/opt/local/sbin:$PATH"
export MANPATH=/opt/local/share/man:$MANPATH
export DISPLAY=:0.0

# Colors
if eval $(gdircolors "$PWD/dircolors/dircolors.256dark") ; then
  alias ls='gls --color=always'
  alias grep='pcregrep --color=auto'
fi
