#!/usr/bin/env bash

export ANSIBLE_BECOME_PASSWORD_FILE="${HOME}/.pas"
export ANSIBLE_CALLBACKS_ENABLED="community.general.yaml,community.general.log_plays"
export ANSIBLE_DISPLAY_ARGS_TO_STDOUT="True"
export ANSIBLE_FORKS="$(nproc)"
export ANSIBLE_LOAD_CALLBACK_PLUGINS="community.general.yaml,community.general.log_plays"
export ANSIBLE_LOG_FOLDER="${HOME}/.cache/ansible/logs"
# export ANSIBLE_LOG_PATH="${HOME}/.cache/ansible/logs/ansible.log"
export ANSIBLE_NO_TARGET_SYSLOG="False"
export ANSIBLE_RETRY_FILES_ENABLED="True"
export ANSIBLE_STDOUT_CALLBACK="yaml"
# export ANSIBLE_LOCAL_TEMP="/tmp/ansible"
# export ANSIBLE_REMOTE_TEMP="/tmp/ansible"
