#!/usr/bin/env bash

# export ANSIBLE_BECOME_PASSWORD_FILE="${HOME}/.pas"
# export ANSIBLE_CACHE_PLUGIN_CONNECTION="${HOME}/.cache/ansible/cache"
# export ANSIBLE_CACHE_PLUGIN_PREFIX="cacheit"
# export ANSIBLE_CALLBACKS_ENABLED="community.general.yaml,community.general.log_plays"
export ANSIBLE_CHECK_MODE_MARKERS="True"
# export ANSIBLE_DISPLAY_ARGS_TO_STDOUT="True"
# export ANSIBLE_FORKS="$(nproc)"
# export ANSIBLE_INVENTORY_CACHE="True"
# export ANSIBLE_INVENTORY_CACHE_PLUGIN="community.general.yaml"
# export ANSIBLE_LOAD_CALLBACK_PLUGINS="community.general.yaml,community.general.log_plays"
# export ANSIBLE_LOCAL_TEMP="/tmp"
# export ANSIBLE_LOG_FOLDER="${HOME}/.cache/ansible/logs"
# export ANSIBLE_LOG_PATH="${HOME}/.cache/ansible/logs/ansible.log"
export ANSIBLE_PARAMIKO_HOST_KEY_CHECKING="no"
# export ANSIBLE_REMOTE_TEMP="/tmp"
# export ANSIBLE_RETRY_FILES_ENABLED="True"
export ANSIBLE_SHOW_TASK_PATH_ON_FAILURE="True"
# export ANSIBLE_STDOUT_CALLBACK="community.general.yaml"
# export ANSIBLE_TRANSPORT="paramiko"
# export ANSIBLE_PIPELINING="True"
# export PERSISTENT_COMMAND_TIMEOUT="120"
# export PERSISTENT_CONNECT_RETRY_TIMEOUT="120"
# export PERSISTENT_CONNECT_TIMEOUT="120"
# export USE_PERSISTENT_CONNECTIONS="True"

# [ssh_connection]
# ssh_args = -o ControlMaster=auto -o ControlPersist=yes ServerAliveInterval=2 ServerAliveCountMax=15
