#!/usr/bin/env bash

[ "${MSYSTEM:-}" = "MINGW64" ] && export MSYS_NO_PATHCONV="1" || true # workaround for git bash on windows
[ "${MSYSTEM:-}" = "MSYS"    ] && export MSYS2_ARG_CONV_EXCL="*" || true # workaround for msys2 bash on windows
