#!/usr/bin/env bash

# Replace PATH
PATH=""
paths=(
  ${HOME}/bin
  ${HOME}/go/bin
  ${HOME}/.cargo/bin
  ${HOME}/.local/bin
  ${HOME}/node_modules/.bin
  ${HOME}/.nvm/versions/node/$(cat ${HOME}/.nvm/alias/default &>/dev/null)/bin
  ${ROCM_PATH:-/opt/rocm}/bin
  ${ROCM_PATH:-/opt/rocm}/llvm/bin
  /opt/llama
  /opt/llama/build/bin
  /opt/sd/build/bin
  /opt/local/bin
  /opt/local/sbin
  /opt/bin
  /opt/sbin
  /var/lib/flatpak/exports/bin
  /usr/games
  /usr/lib/kf5
  /usr/lib/kf6
  /usr/lib/x86_64-linux-gnu/libexec/kf5
  /usr/lib/x86_64-linux-gnu/libexec/kf6
  /usr/local/bin
  /usr/local/sbin
  /usr/share/kf5
  /usr/share/kf6
  /usr/bin
  /usr/sbin
  /bin
  /sbin
  ${HOME}/.krew/bin
  ${HOME}/Nextcloud/scripts
)
for path in "${paths[@]}" ; do
  [ -d "${path}" ] && PATH+=":${path}" || true
done
export PATH
unset paths

export GOPATH="${HOME}/go"
export TMUX_TMPDIR=${HOME}/.local/tmp
