#!/usr/bin/env bash

export UV_ROCM_VER="7.1"
export UV_ROCM_VER_CUR="7.2"
# export UV_CACHE_DIR=/tmp/uv
export UV_COMPILE_BYTECODE="1"
export UV_HTTP_TIMEOUT="120"
export UV_DEFAULT_INDEX="https://rocm.nightlies.amd.com/v2/${AMDGPU_FAMILY:-gfx120X-all}"
export UV_INDEX="https://repo.radeon.com/rocm/manylinux/rocm-rel-${UV_ROCM_VER_CUR}"
export UV_INDEX+=" https://download.pytorch.org/whl/rocm${UV_ROCM_VER_CUR}"
export UV_INDEX+=" https://repo.radeon.com/rocm/manylinux/rocm-rel-${UV_ROCM_VER}"
export UV_INDEX+=" https://download.pytorch.org/whl/rocm${UV_ROCM_VER}"
export UV_INDEX+=" https://wheels.vllm.ai/rocm/vllm"
export UV_INDEX+=" https://pypi.org/simple"
export UV_INDEX_STRATEGY="unsafe-best-match"
export UV_LINK_MODE="copy"
export UV_NO_BUILD_ISOLATION="true"
# export UV_PRERELEASE="if-necessary-or-explicit"
export UV_PRERELEASE="allow"
export UV_PYTHON="python3.12"
export UV_TORCH_BACKEND="rocm${UV_ROCM_VER}"
export UV_VENV_CLEAR="true"
export UV_VENV_SEED="true"
[ -d ${HOME}/venv ] || uv venv ${HOME}/venv || true
export VIRTUAL_ENV=${HOME}/venv
