#!/usr/bin/env bash

command -v bat &>/dev/null && {
  alias cat="bat -pp --tabs=2 --wrap=never"
  alias bat="bat --style=header,rule,changes --decorations=always --paging=never --wrap=never --color=always --tabs=2"
}
