#!/usr/bin/env bash

command -v fzf &>/dev/null && {
  [ -f /usr/share/fzf/completion.bash ] && source /usr/share/fzf/completion.bash
  # [ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash
}
