#!/usr/bin/env bash

# command -v ack &>/dev/null && alias grep="ack -S"
# command -v ag &>/dev/null && alias grep="ag"
command -v ripgrep &>/dev/null && alias grep="ripgrep --pcre2"
command -v rg &>/dev/null && alias grep="rg --pcre2"
alias grep="grep -P"
