#!/usr/bin/env bash

if command -v eza &>/dev/null ; then
  alias  l='eza --git --icons --classify --long'
  alias la='eza --git --icons --classify --all'
  alias ll='eza --git --icons --classify --long --all'
  alias lr='eza --git --icons --classify --long --reverse --time=modified'
  alias ls="eza --git --icons --classify"
  alias lt="eza --git --icons --classify --tree --level=3"
else
  alias ls='ls --color=always'
  alias ll='ls -lhaF --color=always'
  alias lr='ls -lhrt --color=always'
  alias la='ls -A --color=always'
  alias l='ls -CF --color=always'
fi
