#!/usr/bin/env bash

if command -v exa &>/dev/null ; then
  alias  l='exa --git --icons --classify --long'
  alias la='exa --git --icons --classify --all'
  alias ll='exa --git --icons --classify --long --all'
  alias lr='exa --git --icons --classify --long --reverse --time=modified'
  alias ls="exa --git --icons --classify"
  alias lt="exa --git --icons --classify --tree --level=3"
else
  alias ls='ls --color=always'
  alias ll='ls -lhaF --color=always'
  alias lr='ls -lhrt --color=always'
  alias la='ls -A --color=always'
  alias l='ls -CF --color=always'
fi
