#!/usr/bin/env bash

alias rsync='/usr/bin/rsync --no-i-r --info=progress2 --human-readable --partial --progress --update --archive --acls --xattrs --hard-links --exclude={"*cache*","*Cache*"} --compress-choice=zstd --compress-level=4'
