#!/usr/bin/env bash

# sdr () {
alias sdr='systemd-run --user --service-type=exec --wait -dtG' #"${@}"
# }

# sdrb () {
alias sdrb='systemd-run --user --service-type=exec --no-block -dG' #"${@}"
# }

# This allows the function to be run as a script if this file is executed directly
# [[ $- == *i* ]] || sdr "$@"
